title: Holistic Security
email: blog@holisticsecurity.io
description: >- # this means to ignore newlines until "baseurl:"
  Systems Thinking, Holism, Trust, Security & Usability.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://holisticsecurity.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Chilcano
github_username:  Chilcano
linkedin_username:  Chilcano

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

header_pages:
  - index.md
  - blog/index.html
  - about.md

## Pagination for blog posts: https://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: "/blog/pg:num"

#show_excerpts: false
#excerpt_separator: <!-- more -->